### ISSUE TITLE
changing wekan fonts and logo snap instance

### ISSUE THREAD

**Issue by noor-alghamdi** [wekan/wekan-snap#130]
Hello guys , 

I'm trying to change the font and Icon for wekan on snp instance,
i found the logo path following: 
**cd /var/lib/snapd/snap/wekan/968/programs/web.browser/app/**

when I try to delet the old images or replace them , it shows that I can't because it is file system read only, I  need your help, 
same is going for fonts when I try to replace the fonts it says file system read only!

 I even tried with root user but couldn't, 

![Screenshot (873)](https://user-images.githubusercontent.com/65490460/91860337-36ebb580-ec74-11ea-8ebb-98d332fd19cd.png)

any suggestions?

**Comment by noor-alghamdi** [comment]
Any help please?

**Comment by xet7** [comment]
@namacoconut 

What is problem with current Wekan font? Can you not see some text?

**Comment by xet7** [comment]
And what font would be better, so you could see all text ?

**Comment by noor-alghamdi** [comment]
> And what font would be better, so you could see all text ?
@xet7 
the font is perfect and I agree no font will be better, but as I am using this project in my org they need me to apply the standard font, so can you please help!

**Comment by xet7** [comment]
@namacoconut 

Your org needs to contact Commercial Support https://wekan.team/commercial-support/ to discuss your org paying for development of those new features of changing font and logo.

**Comment by noor-alghamdi** [comment]
> @namacoconut
@xet7 
> Your org needs to contact Commercial Support https://wekan.team/commercial-support/ to discuss your org paying for development of those new features of changing font and logo.

these are not new features, there is already a logo and font changing them is not like applying new feature!

**Comment by xet7** [comment]
@namacoconut 

Yes those would be new features, that would need to be developed.

Changing logo feature would be that there is Wekan Admin Panel option where to click and upload logo, or add logo URL.

Font change feature would be menu option where to write new font name.

**Comment by noor-alghamdi** [comment]
@xet7 
I can't find the logo in admin panel 
![Screenshot (875)](https://user-images.githubusercontent.com/65490460/91983579-8ee9f100-ed34-11ea-84b7-f0a5f231b78e.png)

**Comment by xet7** [comment]
@namacoconut 

Yes, because that feature does not exist. That's why payment for developing it would be required.

**Comment by noor-alghamdi** [comment]
@xet7 
good morning mr.lauri
my point is that as it is opensource then I should be able to crack the source code and modify some parameters,hence I was asking about it, not that I need to pay for a logo changing,it is inconvenient

**Comment by xet7** [comment]
@namacoconut 

Yes I know. In some countries people are not used to paying for software, or they don't have enough money, so it is inconvenient.

Also, changing source code is too inconvenient. There is too many steps for normal users. Custom version is hard to update.

So it is easiest that I try to add features for changing font and logo in Admin Panel during this month. That will make it easy for everyone.

**Comment by noor-alghamdi** [comment]
@xet7 
thank you mr.lauri, 
but if there is a way to change it from the source code please let me know, I've got far with configuration I think that chaining parameter from inside the code is not big deal , also I've determined the path of logos and fonts my problem was with permission and how to change them! 

thanks for your cooperation.

**Comment by xet7** [comment]
@namacoconut 

Sure there is a way to change it in source code, if you really are OK making those changes everytime when there is a new update of Wekan. New Wekan versions have security fixes etc, because sometimes there is vulnerabilities found in Node.js etc. If you sometime forget to update manually, and your Wekan is at public Internet, there is a risk getting hacked.

## Building source code on Ubuntu 20.04 64bit

### 1) Clone repo
```
git clone https://github.com/wekan/wekan
cd wekan
```
### 2) Then you change logo images, font etc. Then you install dependencies of Wekan:
```
./rebuild-wekan.sh
```
Write `1` and press Enter to install dependencies.

### 3) Build Wekan
```
./rebuild-wekan.sh
```
Write `2` and press enter to build Wekan to directory `wekan/.build/bundle`.

### 4) Copy bundle directory to server

At server, you only need:
- newest Node.js v12.x LTS and that bundle directory.
- `start-wekan.sh` that you edit for ROOT_URL, MONGO_URL etc

### 5) Setup node as service

If you don't use start-wekan.sh, you can also set Wekan Node.js as service:
https://github.com/wekan/wekan/wiki/Raspberry-Pi#6-running-wekan-as-service

**Comment by xet7** [comment]
Unfortunately it would be inconvenient for me to prioritize non-paid features before already prepaid features.
