### ISSUE TITLE
applying security standards on wekan mongodb

### ISSUE THREAD

**Issue by noor-alghamdi** [wekan/wekan-snap#138]
Good morning mr.lauri,  @xet7 
I have 2 questions,

- Is there any way to modify the below config file ?
` /var/lib/snapd/snap/wekan/1021/bin/config                     .
`

- what can I do  in order to enable security authorization parameter to avoid database access with localhost IP .  

```
` [-root@servername ~] # mongo "mongodb://127.0.0.1:27019/wekan"  ####   We need to disable the localhost from config file 

MongoDB shell version: 3.2.22
connecting to: mongodb://127.0.0.1:27019/wekan
Server has startup warnings:

******# Here is the example for the require changes.**** 
net:
  port: 27018
  bindIp: 10.00.200.18

security:
    authorization: enabled**  `
```

**Comment by namacoconut** [comment]
> Good morning mr.lauri,  @xet7 
> I have 2 questions,
> 
> * Is there any way to modify the below config file ?
>   `/var/lib/snapd/snap/wekan/1021/bin/config                     .`
> * what can I do  in order to enable security authorization parameter to avoid database access with localhost IP .
> 
> ```
> ` [-root@servername ~] # mongo "mongodb://127.0.0.1:27019/wekan"  ####   We need to disable the localhost from config file 
> 
> MongoDB shell version: 3.2.22
> connecting to: mongodb://127.0.0.1:27019/wekan
> Server has startup warnings:
> 
> ******# Here is the example for the require changes.**** 
> net:
>   port: 27018
>   bindIp: 10.00.200.18
> 
> security:
>     authorization: enabled**  `
> ```

**Comment by xet7** [comment]
@namacoconut 

You see mongo related snap commands with:
```
wekan.help | grep mongo
```
Some of those are listed also here:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys#list-of-supported-keys

For example:
```
sudo snap set wekan mongodb-bind-ip='10.00.200.18'
sudo snap set wekan mongodb-port='27018'
```
MongoDB related snap command code is here:
https://github.com/wekan/wekan/blob/master/snap-src/bin/mongodb-control

So if that MONGO_URL does not work properly, you should change that file, test it, and send pull request, like described here https://github.com/wekan/wekan-snap/issues/113#issuecomment-720263569

For example, here is how I added environment variable settings for Snap/Docker/Source etc: https://github.com/wekan/wekan/commit/55252300c601ea40dc8adad1887397b31ceb0bb2

Those environment variables are read at serverside from Snap settings, docker-compose.yml, start-wekan.sh or start-wekan.bat.

In Javascript, those environment variables are read like this:
https://github.com/wekan/wekan/blob/master/server/richer-editor-setting-helper.js#L2
```
const MONGO_URL= process.env.MONGO_URL;
```
If that setting is also needed at browser clientside, then it can be set as public, but in this case you should not do it, because MONGO_URL can contain passwords etc.
```
Meteor.settings.public.MONGO_URL = process.env.MONGO_URL;
```
For creating serverside settings, word `public` is not used, for example:
```
Meteor.settings.MONGO_URL = process.env.MONGO_URL;
```
Because both Meteor settings and environment variables can be read at serverside, above is not usually necessary for just serverside usage.

**Comment by xet7** [comment]
For any existing Wekan feature or fix, you can search [ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md) that has links to code where that feature or fix has been implemented, and look from there would you like to add something related to those.
