### ISSUE TITLE
attachment issue

### ISSUE THREAD

**Issue by fvb-sb** [wekan/wekan-snap#156]
Hi there.

Since the beginning of this week our users complain about broken attachments. Some attachments can be downloaded but some can't. None of them can be viewed and there are no thumbnails.

Server Specs
OS: Ubuntu 18.04 LTS
Webserver: nginx 1.14.0
Wekan: 6.09 (snap)

Client Specs
OS: Win 10 x64 21H2
Browser: Firefox 100.0, Edge 101.0

![2022-05-06_12h58_33](https://user-images.githubusercontent.com/85558230/167121562-743c7f4c-330b-48b1-af16-2a7e4b84d737.gif)

Any clue how to get this sorted?

Thanks in advance!

**Comment by xet7** [comment]
Currently Snap builds are broken, I'm trying to fix them https://github.com/wekan/wekan/issues/4423#issuecomment-1112181784

There could be some attachment migrations still in progress, so that after some time attachments reapprear, or migration could be restarted https://github.com/wekan/wekan/issues/4474#issuecomment-1110533589

Also related is attahment migrations https://github.com/wekan/wekan/issues/4463

Other way would be to try change from Snap to Docker https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/5562
