### ISSUE TITLE
Wekan snap build stuck

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-snap#18]
@kubiko 

When I look at Wekan build status at:
https://code.launchpad.net/~ondrak/+snap/wekan-devel

It says this, and has been stuck since yesterday, time estimate does not change:
"Needs building | in 8 hours (estimated) | amd64 | Primary Archive for Ubuntu"

**Comment by kubiko** [comment]
hi @xet7 
this was caused by long queue on build servers as we restarted package import from debian archive once ubuntu 17.10 was released. Unfortunately at the same time one region went down, so queue got even longer. It should settle and I can see it already improving. So nothing to worry about  :)
