### ISSUE TITLE
How can I upgrade snap to edge build from GIT?

### ISSUE THREAD

**Issue by anlx-sw** [wekan/wekan-snap#27]
I've seen that there is a CI pipeline for wekan-snap to build the "edge" channel from the latest git commits:
https://github.com/wekan/wekan-snap/wiki/Making-releases

If i check my installation I see only version 0.63 - also for the "edge" channel.
![grafik](https://user-images.githubusercontent.com/16399949/35768145-a1b6f856-08f7-11e8-9c28-24848d46f8d0.png)

Is there anything I can do on my installation to enable a current "edge" channel?
Sorry if I could figure this out somehow on my own - the "Making-Releases" article is quite confusing for me.

**Comment by kubiko** [comment]
This repository is no more used for building snap package, instead all snap dependencies are included in main wekan repository. If you want to build snap package your self, simply execute
`$ snapcraft` from root of the wekan source
Otherwise wekan is build every 4 hours when source change is detected, output of build is then automatically published to edge channel. You can see build queue here:
[wekan build](https://code.launchpad.net/~wekan-team/+snap/wekan-devel)

If you want to consume edge builds on your deployment, simply call:
`$ snap refresh wekan --edge`
From now on you device will be automatically updating to latest available version in edge channel. If you want to move back to stable channel, then call:
`$ snap refresh wekan --stable`
You can see revisions available in all channels by calling:
`$ snap info wekan`
