### ISSUE TITLE
Activating privacy features error

### ISSUE THREAD

**Issue by casperNL** [wekan/wekan-snap#38]
Hi there,

I run a webserver on my server together with Wekan, I get the following error:

```
2018/03/18 09:33:13 [sub.host.domain.nl] failed to get certificate: [sub.host.domain.nl] error presenting token: Could not start HTTP server for
Mar 18 09:33:13 sub.host.nl systemd[1]: snap.wekan.caddy.service: Main process exited, code=exited, status=1/FAILURE
Mar 18 09:33:13 sub.host.nl systemd[1]: snap.wekan.caddy.service: Unit entered failed state.
Mar 18 09:33:13 sub.host.nl systemd[1]: snap.wekan.caddy.service: Failed with result 'exit-code'.
```

I want to run Wekan alongside my webserver. Is this possible?

**Comment by casperNL** [comment]
``error presenting token: Could not start HTTP server for challenge -> listen tcp :80: listen: address already in use``

**Comment by xet7** [comment]
When you look at snap install page:
https://github.com/wekan/wekan-snap/wiki/Install

Wekan runs on localhost port 3001.

You can use Caddy to provide automatic Let's Encrypt SSL using ports 80 and 443, you add config to Caddyfile. There is easy examples for Wekan, static hosting, etc. Snap updates Wekan and Caddy automatically.

You seem to have some other webserver already at port 80.

If you'd like to use some other webserver that is more complex to configure, disable caddy:
```
snap set wekan caddy-enabled='false'
```

Then look at Wekan wiki:
https://github.com/wekan/wekan/wiki

At wiki menu at right, there is topic "Webservers" and under that Nginx, Apache and Traefik. From those examples you see how to enable websockets support on your chosen webserver, so that Wekan works correctly. Meteor js framework uses websockets to fast live updates, when there is changes in MongoDB.
