### ISSUE TITLE
Installation steps?

### ISSUE THREAD

**Issue by donpdonp** [wekan/wekan-snap#4]
this is my first encounter with a snap package. the install seemed to have completed fine but I'm at a loss as to what to do next - the wekan server does not appear to be running. the best I can find is 'snap run wekan' which returns `cannot mount /snap/wekan/2/$SNAP_DATA/share at /snap/wekan/2/$SNAP_DATA/shared with options bind. errmsg: No such file or directory`

**Comment by xet7** [comment]
https://github.com/wekan/wekan-snap/wiki

**Comment by donpdonp** [comment]
looks like the wiki page is out of date?

```
$ sudo snap enable wekan
error: cannot enable "wekan": snap "wekan" already enabled
```

```
$ sudo snap connect wekan:network
error: the required argument `<snap>:<slot>` was not provided
```

**Comment by donpdonp** [comment]
also it looks like snap install is already doing what the wiki page says to do. 

```
$ sudo snap interfaces | grep wekan
:network                 wekan
:network-bind            wekan
wekan:mongodb-slot       wekan:mongodb-plug
```

**Comment by xet7** [comment]
Hmm, those were my previous instructions. Seems that only these are needed, you may need to disable and enable it:

Start:
```
sudo snap enable wekan
```

Stop:
```
sudo snap disable wekan
```

Then Wekan is at http://localhost:8080

I myself am also new to snap packages. I have only made small modifications to this snap package originally created by @kubiko

**Comment by xet7** [comment]
I updated wiki. Wiki still most likely does not have all info.

**Comment by xet7** [comment]
Ok it seems that help text is shown with command:

```
wekan.help
```

I updated this to wiki.

@donpdonp 

Did you get it to work?

**Comment by donpdonp** [comment]
the wiki doesnt need 'enable', that already happens with 'install'. nothing has changed on my end, still broken.

```
donp@commons:~$ sudo snap install wekan
wekan (stable) 0.26 from 'wekan' installed
donp@commons:~$ wekan.help
cannot mount /snap/wekan/3/$SNAP_DATA/share at /snap/wekan/3/$SNAP_DATA/shared with options bind. errmsg: No such file or directory
```

taking the error at face value, and assuming an empty SNAP_DATA is okay, the folder 'shared' is not getting created, even though the configure script should be creating the folder

https://github.com/wekan/wekan-snap/blob/master/snap/hooks/configure#L8

```
$ ls -d /snap/wekan/current/sh*
/snap/wekan/current/share
```
`share` is there, but `shared` is not.

**Comment by xet7** [comment]
Does reinstall help?

```
sudo snap remove wekan
sudo snap install wekan
```

**Comment by donpdonp** [comment]
ive removed and installed a few times now. the result is the same.

**Comment by xet7** [comment]
What is your Linux and kernel version?

**Comment by donpdonp** [comment]
```
donp@commons:~$ uname -a
Linux commons 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
donp@commons:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
donp@commons:~$ snap --version
snap    2.16ubuntu3
snapd   2.16ubuntu3
series  16
ubuntu  16.04
```

**Comment by xet7** [comment]
Works for me on newer kernel etc on Xubuntu.
```
lauri@x:~$ uname -a
Linux x 4.8.0-56-generic #61~16.04.1-Ubuntu SMP Wed Jun 14 11:58:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
lauri@x:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

**Comment by donpdonp** [comment]
does the `shared` folder exist on your snap wekan folder?
`$ ls -d /snap/wekan/current/sh*`

**Comment by xet7** [comment]
```
lauri@x:~$ ls -d /snap/wekan/current/sh*
/snap/wekan/current/share
```

**Comment by donpdonp** [comment]
well I have no idea whats going on with the error message I'm seeing. its okay with me if you want to close the ticket.

**Comment by xet7** [comment]
This is still unresolved.

@kubiko

Do you have any idea?

**Comment by xet7** [comment]
@donpdonp 

I don't know have you done these all updates:

```
sudo apt update && sudo apt -y dist-upgrade
```

**Comment by xet7** [comment]
Hmm, I can't seem to reproduce this, maybe you just have a broken install of Ubuntu.

**Comment by kubiko** [comment]
sorry for late response:
- all you need to do is $ snap install wekan
- enable/disbale is not needed, it is there for cases when for example you want to stop wekan, but do not want to uninstall it (uninstall will delete also all user data)
- wekan is service, so apart of help, it does not have any "user executables"
- you can check status of wekan with $ systemctl status snap.wekan.*
  there should be two services, mongodb and wekan running, of either of them is showing error, that would be place to look first. To get detailed look, use $ sudo journalctl -u snap.wekan.wekan.service or snap.wekan.mongodb.service
- content interface for mongodb (wekan:mongodb-slot, wekan:mongodb-plug) is there only for more complex cases where for reason you want to 
 a) share wekan's mongodb instance with other services, use wekan:mongodb-slot
 b) you want to use mongodb instance from some other service, use wekan:mongodb-plug
 so connecting wekan:mongodb-plug to wekan:mongodb-slot really makes no sense :)
As @xet7 suggested, first thing to make sure is that update your machine, so you are running up to date snapd. You can check your version with $ snap version. Currently we are on 2.26
Otherwise shared folders are created under: /var/snap/wekan/current where writable data lives
Databases and other settings live under:
/var/snap/wekan/common/

/snap/wekan/current is read only mount of squashfs wekan's image.

**Comment by donpdonp** [comment]
The journalctl shows the same mount problem reported in the first comment. The good news is upgrading snap from 2.16 to 2.25 fixed the error. Thanks for the help.

**Comment by kubiko** [comment]
Yeah if you are using content interface with snapd before version 2.24 whole snap environment goes off the rails
