### ISSUE TITLE
Store upload scan failed for wekan-release

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-snap#6]
@kubiko 

```
Launchpad uploaded this snap package to the store, but the store failed to
scan it:

  __all__: Can not create a new snap for wekan, the name is already taken and owned by someone else.

--
https://launchpad.net/~wekan-team/+snap/wekan-release/+build/56550
Your team wekan-team is the requester of the build.
```

**Comment by xet7** [comment]
I did download snap from Launchpad and upload it to store, that way I got it released successfully.

Although it would be nice upload to store happened automatically like before today, without download-upload steps.

**Comment by kubiko** [comment]
Yeah I noticed the error. I'll try to find out what went wrong. There is no reason it should stop working like it was before....

**Comment by kubiko** [comment]
bug tracking this problem is here:
https://bugs.launchpad.net/launchpad/+bug/1704824


On Sat, 15 Jul 2017, at 04:16, Ondra Kubik wrote:
> Yeah I noticed the error. I'll try to find out what went wrong. There is no reason it should stop working like it was before....> 
> Sent from my iPhone
> 
> On 15 Jul 2017, at 01:22, Lauri Ojansivu <notifications@github.com> wrote:>> I did download snap from Launchpad and upload it to store, that way I got it released successfully.>> Although it would be nice upload to store happened automatically like before today, without download-upload steps.>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub[1], or mute the thread[2]. >> 


---------
Quote - Soap (Lock, Stock and Two Smoking Barrels):
- A minute ago this was the safest job in the world. Now it's turning into a bad day in Bosnia.mailto: ondra@ondra.org



Links:

  1. https://github.com/wekan/wekan-snap/issues/6#issuecomment-315495762

**Comment by xet7** [comment]
I think this is fixed already, uploads seems to work ok.
