### ISSUE TITLE
Impossible to restore backup, conflicts with duplicate key

### ISSUE THREAD

**Issue by ghost** [wekan/wekan-snap#62]
Hello, I want to restore a backup but when I run the restore AC fails because it generates me duplicate key conflicts.
May I have to execute a command to empty the database before?

**Comment by xet7** [comment]
https://github.com/wekan/wekan-snap/wiki/Backup-and-restore#stop-wekan-and-restore

**Comment by vitobotta** [comment]
Hi, I am having exactly the same issue. I backup and restore as explained in the wiki linked above, but when I restore I get lots of errors like the below and the data isn't actually restored. How to perform a restore correctly with the snap installation? Thanks.

```
E11000 duplicate key error collection: wekan.boards index: _id_ dup key: { : "oksdYm2BSjng4g9ZM" }
```

**Comment by xet7** [comment]
@vitobotta 

When you are in the directory that has dump subdirectory that contains wekan backup:
```
mongorestore --drop --noIndexRestore --port 27019
```

**Comment by xet7** [comment]
@vitobotta 

Before restoring backup, old data has usually already indexes. That's why old data needs to be deleted before restory by including option `--drop`.

**Comment by vitobotta** [comment]
Hi, thanks for your reply!  :)

I am now using scripts taken from the main wiki slightly modified (see [backup script](https://gist.github.com/vitobotta/e3fc9e289d22a893203c42d80e757722) and [restore script](https://gist.github.com/vitobotta/ff20ac8c6736f88ddc6f80cb3acca789)) because this way I have a little more control. These scripts work fine so for now I'm good. 

Thanks!

**Comment by xet7** [comment]
@vitobotta 

Thanks! I added your scripts to wiki:
https://github.com/wekan/wekan/wiki/Backup

**Comment by p2635** [comment]
I know this issue is closed but as a new user using wekan locally via snap, there does not seem to be a clear way for me to backup wekan data. The wiki led me to these scripts but I have no idea how to use them properly, there is no guidance text. I'm not very good with Linux yet but I did give it a try.

With the backup script, I successfully tweaked it to dump a tar file but I needed to to change the parent_dir with the path to my desired location (I tested it on the downloads folder).

For the restore script, running it does nothing and says the command is not recognised. I am guessing that I'm supposed to add it as a custom function for bash so I can do makesRestore (file) whenever I like.

Can someone teach me or point me to where I can learn to:
1. Completely backup current snapshot of all my wekan data
2. Restore snapshot, I assume I have to delete old data like the above comments say but I have to log into mongo through the command line?

*If it is important, I am using Kubuntu 20.04.

I can see there is an option to export boards one by one into JSON but that is not enough for me. Am I wrong is saying there isn't currently a user friendly way to backup/restore data through the UI? Thanks in advance. If someone could update the wiki, that would be even better so other people can benefit.

**Comment by xet7** [comment]
@p2635 

On that computer that has Wekan Snap installed, you add these lines to .bashrc, exit terminal, and open terminal again (or, ssh to server again), and then backup or restore:
https://github.com/wekan/wekan/wiki/Backup#using-snap-mongo-commands-on-your-bash-cli

Wekan Snap does contain required commands for making backups, and restoring them, so above just adds those to your path.

You can also create .zip file of that dump directory:
```
sudo apt install zip unzip
zip -r backup-2020-07-22.zip dump
```

**Comment by xet7** [comment]
@p2635 

For saving snap settings to textfile, you can use command:
```
sudo snap get wekan > snap-settings.txt
```
If you have Caddy webserver configured, you can also backup that file from:
```
/var/snap/wekan/common/Caddyfile
```

**Comment by xet7** [comment]
In general, all Wekan data is at `/var/snap/wekan/common` directory. But there is raw MongoDB database files, and it's not a good idea to backup those, like it is not a good idea to backup raw MySQL database files, because if raw files are somehow corrupted, you would not be able to restore. It's much safer to dump those to from database to a format that dump/restore command can handle.

**Comment by xet7** [comment]
Sure it's possible go all the way from raw database files => dump format => plain text JSON files if that's really necessary:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

And it's possible to save attachments from MongoDB database files with nosqlbooster.

**Comment by p2635** [comment]
Thanks @xet7 for your help.

> On that computer that has Wekan Snap installed, you add these lines to .bashrc, exit terminal, and open terminal again (or, ssh 
to server again), and then backup or restore:
https://github.com/wekan/wekan/wiki/Backup#using-snap-mongo-commands-on-your-bash-cli

It prompted me to `Command 'mongodump' not found, but can be installed with:
sudo apt install mongo-tools` but I got past that by installing it. I was eventually able to do `mongodump --port 27019` but doing this and then zipping it is way too manual for me.

Therefore I think I would prefer to learn how to use the .sh scripts, so how exactly am I meant to use them? My initial impression was to create 2 files (wekan-backup.sh and wekan-restore.sh), copy the content over and then run them. In my previous comment, I said that I successfully tweaked the backup script but I needed to to change the parent_dir to make it work. It doesn't work right off the bat. The restore script also doesn't work, it says the command doesn't exist.

Anyway, you mentioned I am supposed to add them to .bashrc. If that is the case then why doesn't the backup script have a function name? In restore, I can see it is called `makesRestore()`, so confused. Even if I add them to .bashrc, what do I do next?

> For saving snap settings to textfile, you can use command: sudo snap get wekan > snap-settings.txt

Yup, success.

Thank you for being patient with me. I know it may be obvious for most of you terminal experts so forgive me as I am just a beginner. To sum it up, I want an easy way to just backup my data but there doesn't seem to be one. If this 'Snap backup-restore v2' is the easiest way then I hope someone can update the documentation to be a clear step by step guide instead of a dump of the script.

**Comment by xet7** [comment]
@p2635 

It is possible to make scheduled backups offsite with rclone that support these many clouds etc: https://rclone.org

I added more descriptions to commands at:
https://github.com/wekan/wekan/wiki/Backup#cloud-backup-with-rclone

**Comment by p2635** [comment]
I'm not backing up to the cloud, I'm only backing up locally therefore I want to learn to use wekan-backup.sh and wekan-restore.sh. Is it worth me posting in the forums instead of here to avoid this getting longer? thanks @xet7

**Comment by xet7** [comment]
@p2635 

Please do not post to forums about features, fixes etc. This is the correct place. There is no reason to avoid, you can add comments to any issues.

**Comment by p2635** [comment]
Ok @xet7 , maybe it was lost in the comments but here is my main question. how do I use wekan-backup.sh and wekan-restore.sh) properly?

1. Add them to .bashrc
2. ??

**Comment by xet7** [comment]
@p2635 

No, you don't add those to .bashrc.

I added more info and moved that scheduled backup to top of page https://github.com/wekan/wekan/wiki/Backup

I try to later add info about restore.

Hmm, maybe this could be somehow made more easier. For example, if Wekan automatically would create some backups in some easy format. I'll think.

**Comment by p2635** [comment]
Thanks @xet7, I know all this development stuff takes time so if you can't do it straight away don't worry. I will try to read through the additional information that you wrote. I am just excited to use wekan for the first time and don't want to lose my data. As you guys wrote on the wiki, backup is essential on a daily basis.
